# Generated by Django 5.2.6 on 2025-09-19 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_remove_participant_contest_remove_participant_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='published_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'modo'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Publié par'),
        ),
    ]
