# Generated by Django 5.2.6 on 2025-09-21 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_alter_submission_published_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='submissions/medias/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='contests.submission')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
