# Generated by Django 5.2.6 on 2025-09-22 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_submissionmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionmedia',
            options={'ordering': ['order'], 'verbose_name': 'Média de soumission', 'verbose_name_plural': 'Médias de soumission'},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='media',
        ),
        migrations.AlterField(
            model_name='submissionmedia',
            name='media',
            field=models.FileField(help_text='Téléchargez une photo (.jpg, .jpeg, .png) ou une vidéo (.mp4, .mov)', upload_to='submissions/', verbose_name='Média (photo ou vidéo)'),
        ),
        migrations.AlterField(
            model_name='submissionmedia',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='submissionmedia',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='contests.submission', verbose_name='Soumission'),
        ),
    ]
