# Generated by Django 5.2.6 on 2025-09-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_alter_submissionmedia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='moderator_text',
            field=models.TextField(blank=True, null=True, verbose_name='Texte du modérateur'),
        ),
    ]
